name: CI - Test, Coverage, Docker Build & Run

on:
  push:
    branches: [ main, add-ci-docker ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest --cov=app

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t flask-ci-docker .

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 --name test-container flask-ci-docker
          sleep 5
          curl http://localhost:5000
          docker logs test-container
          docker stop test-container
          docker rm test-container
